# Example configuration for the Deauth Whitelist Plugin
# These settings should be added to /etc/pwnagotchi/config.toml

# Enable the plugin
main.plugins.deauth_whitelist.enabled = true

# Optional: Alternative path for the whitelist file
# main.plugins.deauth_whitelist.whitelist_file = "/custom/path/to/whitelist.json"