# Beispiel-Konfiguration für das Deauth Whitelist Plugin
# Diese Einstellungen sollten in /etc/pwnagotchi/config.toml hinzugefügt werden

# Plugin aktivieren
main.plugins.deauth_whitelist.enabled = true
