# Beispiel-Konfiguration f端r das Deauth Whitelist Plugin
# Diese Einstellungen sollten in /etc/pwnagotchi/config.toml hinzugef端gt werden

# Plugin aktivieren
main.plugins.deauth_whitelist.enabled = true

# Optional: Alternativer Pfad f端r die Whitelist-Datei
# main.plugins.deauth_whitelist.whitelist_file = "/custom/path/to/whitelist.json"

# Andere relevante Pwnagotchi-Einstellungen f端r Webserver
ui.web.enabled = true
ui.web.address = "0.0.0.0"
ui.web.port = 8080
ui.web.username = "changeme"
ui.web.password = "changeme"
